import {test} from 'node:test';
import assert from 'node:assert/strict';
import {create,join,identify,view,action as rawAction} from '../game.js';
function action(room,player,data){rawAction(room,player,{match:room.match,...data});}
test('delayed requests from a previous match are rejected',()=>{const m=match();guess(m,m.red,'word','pepper');guess(m,m.blue,'word','apple');const previous=m.room.match;action(m.room,m.red,{action:'rematch'});action(m.room,m.blue,{action:'rematch'});assert.throws(()=>rawAction(m.room,m.red,{match:previous,action:'secret',value:'oldword'}));assert.equal(m.red.secret,null);});
function match(){const {room,player:red}=create('Red');const {player:blue}=join(room.code,'Blue');action(room,red,{action:'secret',value:'APPLE'});action(room,blue,{action:'secret',value:'PEPPER'});return {room,red,blue};}
function guess(m,p,kind,value){action(m.room,p,{action:'guess',kind,value,round:m.room.round});}
test('private view, validation, capacity and seat identity',()=>{const m=match();assert.throws(()=>join(m.room.code,'Third'));assert.throws(()=>join('XXXXXX','Bad'));assert.throws(()=>identify(m.room.code,'fake'));assert.equal(identify(m.room.code,m.red.token).player,m.red);const v=view(m.room,m.red);assert.equal(v.words,undefined);assert.ok(!JSON.stringify(v).includes('PEPPER'));assert.equal(v.players[1].secret,undefined);assert.throws(()=>action(m.room,m.red,{action:'secret',value:'OTHER'}));assert.throws(()=>guess(m,m.blue,'letter','P'));assert.throws(()=>guess(m,m.red,'letter','PP'));assert.equal(m.room.turn,0);});
test('counts and hidden lengths, alternating turns, wrong words',()=>{const m=match();guess(m,m.red,'letter','p');assert.equal(m.red.history[0].feedback,'3 Ps');assert.throws(()=>guess(m,m.red,'letter','e'));guess(m,m.blue,'letter','h');assert.equal(m.blue.history[0].feedback,'No H');guess(m,m.red,'length',5);assert.equal(m.red.history[1].feedback,'Incorrect length.');guess(m,m.blue,'length',5);assert.equal(m.blue.history[1].feedback,'Correct length!');guess(m,m.red,'word','orange');guess(m,m.blue,'letter','e');assert.equal(m.blue.history[2].feedback,'1 E');assert.equal(m.room.round,4);assert.equal(m.room.phase,'playing');assert.throws(()=>action(m.room,m.red,{action:'guess',kind:'letter',value:'p',round:3}));});
for(const result of ['RED','BLUE','draw'])test(`${result} result only after BLUE, then bilateral rematch`,()=>{const m=match();guess(m,m.red,'word',result==='BLUE'?'wrong':'pepper');assert.equal(m.room.phase,'playing');assert.equal(view(m.room,m.blue).words,undefined);guess(m,m.blue,'word',result==='RED'?'wrong':'apple');assert.equal(m.room.result,result);assert.deepEqual(view(m.room,m.red).words,['APPLE','PEPPER']);assert.throws(()=>guess(m,m.red,'word','pepper'));action(m.room,m.red,{action:'rematch'});assert.equal(m.room.phase,'result');assert.throws(()=>action(m.room,m.red,{action:'rematch'}));action(m.room,m.blue,{action:'rematch'});assert.equal(m.room.phase,'submission');assert.equal(m.room.round,1);assert.equal(m.red.history.length,0);assert.equal(m.red.secret,null);action(m.room,m.red,{action:'secret',value:'fresh'});action(m.room,m.blue,{action:'secret',value:'words'});assert.equal(m.room.phase,'playing');assert.equal(m.room.turn,0);});
test('invalid secrets do not consume submission',()=>{const {room,player}=create('Test');join(room.code,'Friend');for(const value of ['a','two words','123','éé','a'.repeat(21)])assert.throws(()=>action(room,player,{action:'secret',value}));assert.equal(player.secret,null);});

